/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { useAnimationMixer } from "../hooks/useAnimationMixer";

type GLTFResult = GLTF & {
  nodes: {
    Object_0: THREE.Mesh;
  };
  materials: {
    Material_0_COLOR_0: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "KeyAction";
type GLTFAction = Record<ActionName, THREE.AnimationAction>;

export default function Parrot({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>() as React.MutableRefObject<THREE.Group>;
  const { nodes, materials, animations, scene } = useGLTF(
    "/assets/models/Parrot.glb"
  ) as GLTFResult;
  const { clips } = useAnimations(animations);
  const mixer = useAnimationMixer(scene, clips);
  useFrame((_, delta) => {
    mixer.update(delta);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Parrot"
          geometry={nodes.Object_0.geometry}
          material={materials.Material_0_COLOR_0}
          morphTargetDictionary={nodes.Object_0.morphTargetDictionary}
          morphTargetInfluences={nodes.Object_0.morphTargetInfluences}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Parrot.glb");
